test: use http instead of gqtp in RemoteDatabase tests
Because:
groonga-client uses gqtp as default.
If gqtp server isn't launched, these tests cause below errors.

E
===============================================================================
Error: test_load_records(TestRemoteDatabase::TestRecords)
  Errno::ECONNREFUSED: Connection refused - connect(2)
test/epub-searcher/remote_database_test.rb:49:in `setup'
===============================================================================
E
===============================================================================
Error: test_load_records(TestRemoteDatabase::TestRecords)
  NoMethodError: undefined method `close' for nil:NilClass
test/epub-searcher/remote_database_test.rb:53:in `teardown'
===============================================================================
E
===============================================================================
Error: test_setup_database(TestRemoteDatabase::TestSetup)
  Errno::ECONNREFUSED: Connection refused - connect(2)
test/epub-searcher/remote_database_test.rb:6:in `setup'
===============================================================================
E
===============================================================================
Error: test_setup_database(TestRemoteDatabase::TestSetup)
  NoMethodError: undefined method `close' for nil:NilClass
test/epub-searcher/remote_database_test.rb:10:in `teardown'
===============================================================================